name: CI/CD - Release & Production
 
on:

  push:
    branches: [ main, master, release ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:
    
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2     
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        run: | 
             docker build . --file SME.Integracao.Serap.Worker/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-integracao
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-prova-serap-integracao  
 
  deploy-release:
  
    runs-on: master
    if: ${{ github.ref == 'refs/heads/release' }}
    needs: [ build ]    
    environment:
      name: release
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v1.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-integracao
          NAMESPACE: sme-serap-estudante
          
  deploy-master:
  
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [ build ]    
    environment:
      name: production
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v1.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: sme-prova-serap-integracao
          NAMESPACE: sme-serap-estudante
          
